# Project information
site_name: APTITUDE Technical Specification
site_description: APTITUDE Technical Specification
site_author: APTITUDE Consortium
site_url: https://aptitude-consortium.github.io/aptitude-eudi-wallet-specs/

# Repository
repo_name: APTITUDE-Consortium/aptitude-eudi-wallet-specs
repo_url: https://github.com/APTITUDE-Consortium/aptitude-eudi-wallet-specs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 APTITUDE Consortium

# Configuration for MkDocs Material theme
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png

extra_css:
  - media/extra.css

plugins:
  - tags
  - exclude:
      glob:
        - 'rulebook/wp2-trust-specifications/README.md'
        - 'rulebook/wp2-trust-specifications/CONTRIBUTING.md'
  - search
  - ezglossary:
      strict: true
      ignore_case: true
      plurals: en
      markdown_links: true
      tooltip: full
      templates: docs/overrides/ezglossary
      sections:
        - roles
        - components
        - credentials
        - protocols
  - git-revision-date
  - git-revision-date-localized:
      locale: en
      fallback_to_build_date: true
      type: datetime


markdown_extensions:
  - footnotes
  - sane_lists
  - tables
  - def_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Rulebooks:
    - Overview: rulebook/index.md
    - mVRC: rulebook/wp5/mVRC-rulebook.md
    - Trust Framework: rulebook/wp2-trust-specifications/deliverable-2.1-trust.md
  - RFCs:
    - Overview: horizontal-RFCs/index.md
    - RFC-01 Credential Issuance Profile: horizontal-RFCs/RFC001.md
    - RFC-02 Presentation Profile: horizontal-RFCs/RFC002.md
  - Standards: standards.md
  - Glossary: 
    - Glossary: glossary.md
    - Definitions: glossary-definitions.md


